"""Phase 6A.2: Add authentication fields to User and Rescue models

Revision ID: 1893468fe18b
Revises: c260af4637a4
Create Date: 2025-05-27 14:18:23.304712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1893468fe18b'
down_revision = 'c260af4637a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rescue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('primary_contact_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('primary_contact_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('primary_contact_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_consent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('marketing_consent', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['primary_contact_email'])
        batch_op.create_foreign_key(None, 'user', ['approved_by'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rescue_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rescue_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('rescue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('marketing_consent')
        batch_op.drop_column('data_consent')
        batch_op.drop_column('primary_contact_phone')
        batch_op.drop_column('primary_contact_email')
        batch_op.drop_column('primary_contact_name')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approved_date')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
