"""Initial schema with Rescue and Dog models

Revision ID: 4e30a4e16d95
Revises: 
Create Date: 2025-05-12 22:24:56.491023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e30a4e16d95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescues',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rescues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rescues_name'), ['name'], unique=True)

    op.create_table('dogs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rescue_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dogs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dogs_rescue_id'), ['rescue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dogs_rescue_id'))
        batch_op.drop_index(batch_op.f('ix_dogs_name'))

    op.drop_table('dogs')
    with op.batch_alter_table('rescues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rescues_name'))

    op.drop_table('rescues')
    # ### end Alembic commands ###
