"""Add composite indexes to AuditLog for query optimization

Revision ID: 7b3fd44383fc
Revises: 62857dc28040
Create Date: 2025-05-25 15:04:22.826529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3fd44383fc'
down_revision = '62857dc28040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_rescue_id_timestamp', ['rescue_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_audit_log_resource_type_id_timestamp', ['resource_type', 'resource_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_audit_log_user_id_action_timestamp', ['user_id', 'action', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_user_id_action_timestamp')
        batch_op.drop_index('ix_audit_log_resource_type_id_timestamp')
        batch_op.drop_index('ix_audit_log_rescue_id_timestamp')

    # ### end Alembic commands ###
