"""Add category and dosage info to MedicinePreset

Revision ID: 8af6c7934fe3
Revises: 77dfa962f8bb
Create Date: 2025-05-22 14:55:06.092957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8af6c7934fe3'
down_revision = '77dfa962f8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_preset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('default_dosage_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('suggested_units', sa.String(length=255), nullable=True))

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('medicine_preset', schema=None) as batch_op:
        batch_op.drop_column('suggested_units')
        batch_op.drop_column('default_dosage_instructions')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
