"""Add approx_age to Dog model

Revision ID: a559af50b5c7
Revises: 4e30a4e16d95
Create Date: 2025-05-13 23:49:56.702977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a559af50b5c7'
down_revision = '4e30a4e16d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approx_age', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.drop_column('approx_age')

    # ### end Alembic commands ###
