"""add_form_field_to_dog_medicine

Revision ID: a7b10842fa13
Revises: 8af6c7934fe3
Create Date: 2025-05-22 16:26:11.698519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b10842fa13'
down_revision = '8af6c7934fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, update any NULL values in existing data
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE dog_medicine SET unit = 'mg' WHERE unit IS NULL"))
    connection.execute(sa.text("UPDATE dog_medicine SET frequency = 'daily' WHERE frequency IS NULL"))
    
    with op.batch_alter_table('dog_medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form', sa.String(length=100), nullable=True))
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_medicine', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('form')

    # ### end Alembic commands ###
