"""Intial migration

Revision ID: b3c3da2079c0
Revises: 
Create Date: 2025-05-18 23:47:33.030361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c3da2079c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('adoption_status', sa.String(length=50), nullable=True),
    sa.Column('intake_date', sa.Date(), nullable=True),
    sa.Column('microchip_id', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('medical_info', sa.Text(), nullable=True),
    sa.Column('rescue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('invite_code', sa.String(length=32), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('rescue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('user')
    op.drop_table('dog')
    op.drop_table('rescue')
    # ### end Alembic commands ###
