"""Initial clean slate for phase 2

Revision ID: f17680ad3dbf
Revises: 
Create Date: 2025-05-19 14:50:01.476098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17680ad3dbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rescue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rescue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.String(length=20), nullable=True),
    sa.Column('breed', sa.String(length=120), nullable=True),
    sa.Column('adoption_status', sa.String(length=50), nullable=True),
    sa.Column('intake_date', sa.Date(), nullable=True),
    sa.Column('microchip_id', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('medical_info', sa.Text(), nullable=True),
    sa.Column('rescue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicine_preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rescue_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('default_unit', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('invite_code', sa.String(length=32), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('rescue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('rescue_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('recurrence', sa.String(length=20), nullable=True),
    sa.Column('recurrence_value', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.id'], ),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescue.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['appointment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog_medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('rescue_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=120), nullable=True),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('frequency_value', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dog.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicine_preset.id'], ),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dog_medicine_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_medicine_id', sa.Integer(), nullable=False),
    sa.Column('date_given', sa.Date(), nullable=True),
    sa.Column('given_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dog_medicine_id'], ['dog_medicine.id'], ),
    sa.ForeignKeyConstraint(['given_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('dog_medicine_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reminder_time', sa.String(length=20), nullable=True),
    sa.Column('custom_offset', sa.Integer(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['dog_medicine_id'], ['dog_medicine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    op.drop_table('dog_medicine_history')
    op.drop_table('dog_medicine')
    op.drop_table('appointment')
    op.drop_table('user')
    op.drop_table('medicine_preset')
    op.drop_table('dog')
    op.drop_table('appointment_type')
    op.drop_table('rescue')
    # ### end Alembic commands ###
