"""Add personality fields to Dog model

Revision ID: f53ad914b398
Revises: d365f7fe8597
Create Date: 2025-06-17 23:19:34.984609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53ad914b398'
down_revision = 'd365f7fe8597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personality_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('energy_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('social_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('special_story', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('temperament_tags', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('temperament_tags')
        batch_op.drop_column('special_story')
        batch_op.drop_column('social_notes')
        batch_op.drop_column('energy_level')
        batch_op.drop_column('personality_notes')

    # ### end Alembic commands ###
